### PR TITLE
#If statements that work with all libraries.

### PR DESCRIPTION
**Pull request by 0b1kn00b**
like #3, except it took longer

### CODE REVIEW

**Comment by RealyUniqueName** [comment]
AFAIK you just need to replace such characters with underscore for `#if`s:
```
-lib flixel-tools

#if flixel_tools
#end
```

**Comment by jonasmalacofilho** [comment]
> Any identifier is replaced by the value of the compiler flag by the same name. Note that -D some-flag from command line leads to the flags some-flag and some_flag to be defined.
—_The manual: [Conditional Compilation](http://haxe.org/manual/lf-condition-compilation.html)_

**Comment by 0b1kn00b** [comment]
Argh. Thanks, didn't know, sorry to bother you.

What about dots? like for thx.core?

regards,
laurence

**Comment by ncannasse** [comment]
Can we close this?

**Comment by 0b1kn00b** [comment]
what about `.` as in `thx.core`. Doesn't look like it works.

**Comment by fponticelli** [comment]
It works with `thx_core` I believe.

**Comment by RealyUniqueName** [comment]
All "non-identifier-friendly" characters are converted to underscores.

**Comment by 0b1kn00b** [comment]
I'm not finding that here.
```Ubuntu 14.04.3 LTS```
```
Haxe 3.3.
commit: 70242f83dcf6eb81ab2ebec1b720fd4c70373c1c
```

**Comment by 0b1kn00b** [comment]
Ok, it works while *not* using the `dev` version.

```
Classpath : /media/i/src/haxe/lib/tink_core/git/src/;/media/i/src/haxe/lib/thx,core/0,40,1/src/;/media/i/src/haxe/lib/utest/1,4,1/src/;src/test/haxe/;src/main/haxe/;;/home/dayz/i/src/haxe/haxe/std/neko/_std/;/home/dayz/i/src/haxe/haxe/std/
Defines : utest=1.4.1;true;tink_core=0.0.0;thx_core;thx.core=0.40.1;sys;source-header=Generated by Haxe 3.3.0;neko;haxe_ver=3.3;haxe3;dce=std
```

**Comment by RealyUniqueName** [comment]
I'm using dev and it works too )

**Comment by 0b1kn00b** [comment]
git version? :|

**Comment by RealyUniqueName** [comment]
yes

**Comment by RealyUniqueName** [comment]
This one: 440226d

**Comment by 0b1kn00b** [comment]
I mean, if you set  `thx.core` to the git version, it doesn't work

**Comment by 0b1kn00b** [comment]
```haxelib git thx.core https://github.com/fponticelli/thx.core.git master src```

**Comment by RealyUniqueName** [comment]
Still works:
```
$ haxe -lib thx.core -x Test
Test.hx:8: {source-header => Generated by Haxe 3.3.0, thx.core => 0.40.1, haxe_ver => 3.3, thx_core => 1, sys => 1, dce => std, true => 1, neko => 1, haxe3 => 1}
```

**Comment by 0b1kn00b** [comment]
I'm getting "thx.core=0.0.0", maybe that's it.

**Comment by RealyUniqueName** [comment]
Did you try running my code?

**Comment by 0b1kn00b** [comment]
Test.hx:8: {source-header => Generated by Haxe 3.3.0, thx.core => 0.0.0, haxe_ver => 3.3, sys => 1, dce => std, true => 1, neko => 1, haxe3 => 1}

**Comment by 0b1kn00b** [comment]
On my set up, using `git` makes `thx.core => 0.0.0`

**Comment by 0b1kn00b** [comment]
This is still a thing. 
Using `thx.core` installed via git, the version reports as `0.0.0` and the conditional compilation doesn't trigger. `thx.core` installed via haxelib works as it should.

**Comment by RealyUniqueName** [comment]
I think you should start an issue on haxelib repo

**Comment by 0b1kn00b** [comment]
will do

**Pull request closed without merging**
