### PR TITLE
Command to init empty Haxe project.

### PR DESCRIPTION
**Pull request by dmitryhryppa**
Providinga a Haxe compiler command to create an empty project in the selected folder.
`haxe --init cpp js hl`

Which will generate something like this:
```
├───.vscode
│   ├── settings.json
│   └── tasks.json
│
├── out
│   ├── cpp
│   ├── hl
│   └── js
│
├── src
│   └── Main.hx
│
├── build.cpp.hxml
├── build.hl.hxml
├── build.js.hxml
├── common.hxml
```

[Rendered version](https://github.com/dmitryhryppa/haxe-evolution/blob/init-command/proposals/0000-init-command.md)

### CODE REVIEW

**Comment by ncannasse** [comment]
This should definitely not be part of the compiler, could be added to
vshaxe commands instead.

Le lun. 21 janv. 2019 19:12, Dmitry Hryppa <notifications@github.com> a
écrit :

**Comment by markknol** [comment]
I once created a haxelib called [hxnew](https://github.com/markknol/hxnew) which does something like that, maybe I should add vscode support for it.

**Comment by Simn** [comment]
This is outside the scope of a compiler.

**Comment by dmitryhryppa** [comment]
> This should definitely not be part of the compiler
> This is outside the scope of a compiler.

I thought about TypeScript compiler which has that option, that's why I did this proposal here :) 


> @markknol 
>I once created a haxelib called hxnew which does something like that, maybe I should add vscode support for it.
Or indeed, could be added to vshaxe commands.

Oh, this is a very cool thing. Would be awesome if this can be a part of at least VSHaxe.

**Comment by fullofcaffeine** [comment]
> Oh, this is a very cool thing. Would be awesome if this can be a part of at least VSHaxe.

Or at least mentioned in the haxe.org website. This can help reduce some friction when first trying Haxe.

**Pull request closed without merging**
