### PR TITLE
Inlining functions at call location

### PR DESCRIPTION
**Pull request by YellowAfterlife**
Allow requesting a function to be inlined at call location

[Rendered version](https://github.com/YellowAfterlife/haxe-evolution/blob/master/proposals/0000-inline-calls.md)

### CODE REVIEW

**Comment by Simn** [comment]
> inline is not currently used in expression syntax at all

That is not _entirely_ true because `inline function` exists at expression level. However, that does not cause any grammar problems.

I'm very much in favor of this. My biggest concern is the required AST change.

**Comment by ncannasse** [comment]
Can AST be parsed with a metadata ? "inline expr" would be equivalent of "@:inline expr" , and we could have the same of "inline function foo()" actually.

**Comment by Simn** [comment]
We could do that, but I think with a major version change we should do it properly and add EInline, similar to EUntyped.

**Comment by ncannasse** [comment]
We would only allow inlining of `@:inline ECall`, not add "inline" meta to whole expression typing as we do for normal metadata.

**Comment by Simn** [comment]
I agree with that.

**Pull request merged**
