### PR TITLE
Package alias

### PR DESCRIPTION
**Pull request by hydroper**
A little extra syntax proposal

[Rendered](https://github.com/hydroper/haxe-evolution/blob/master/proposals/0000-package-alias.md#package-alias)

### CODE REVIEW

**Comment by Simn** [comment]
The `.*` confuses me here, my intuition would be `import ecma262.temporal as Temporal;`.

**Comment by hydroper** [comment]
@Simn In ActionScript packages are not to be mixed with different symbols in name resolution, so that's one reason I see for `.*`.

**Comment by fy0** [comment]
Can't agree more.

**Comment by EliteMasterEric** [comment]
@hydroper Did you delete this PR by accident? Can you restore it?

**Comment by linuxmetro** [comment]
@EliteMasterEric Hi, I've broken my phone chip sometime ago and lost access to @hydroper :(

**Pull request closed without merging**
