### PR TITLE
Polymorphic `this` types

### PR DESCRIPTION
**Pull request by matulkum**
[Rendered version](https://github.com/matulkum/haxe-evolution/blob/master/proposals/0000-polymorphic-this-types.md)

### CODE REVIEW

**Comment by nadako** [comment]
I added a link to the rendered version so one can easily view the proposal markdown document.

**Comment by EricBishton** [comment]
As a first thought, isn't this what static extensions are supposed to solve?  Why would that mechanism be insufficient?  (https://try.haxe.org/#01b82)

```haxe
using Test.Calculator;

class BasicCalculator {
    public var result = 0.0;

    public function new () {}

    public function add(a: Int): BasicCalculator {
        result += a;
        return this;
    }
}

class Calculator {
    public static function sin(c:BasicCalculator): BasicCalculator {
        c.result = Math.sin(c.result);
        return c; 
    }
}

class Test {
    static function main() {
        var calculator = new BasicCalculator();
        var result = calculator.add(2).add(3).sin().result; // <-- Totally possible in current Haxe
    }
}
```

**Comment by matulkum** [comment]
@EricBishton I agree that you solved this specific example with a static extensions. In general it is not the same though: you cannot override a method in BasicCalculator. You can also just add methods, not properties. You could not extend BasicCalculator with a static extension like in this example:

```haxe
enum Mode {
	RAD;
	DEG;
}
class Calculator extends BasicCalculator {
    public var mode: Mode; 
    
    public function sin() {
        if( this.mode == RAD)
	        this.result = Math.sin(this.result);
        else
            this.result = Math.sin(this.result/180*Math.PI);
        return this;       
    }
}

class Test {
    static function main() {
        var calculator = new Calculator();
        calculator.mode = DEG;
        var result = calculator.add(2).add(3).sin().result;
    }
}
```

Also static Extensions do not help in creating Extern definitions.

**Comment by markknol** [comment]
I wonder if this should be a type inference feature, if you leave out the return type definition, it works? Then `this` stays the same in its context, just as we have now.

**Comment by matulkum** [comment]
@markknol Actually we do NOT have that now. Currently the return type `BasicCalculator.add()` will infer to `BasicCalculator` always, even if it is called from `Calculator`.. and I think rightly so.

By providing `this` as an option to implicitly define the return type you can have it both ways and you have actual control. See also @nadako comment at the community forum: http://community.haxe.org/t/feature-proposal-polymorphic-this-types/174/5

**Comment by markknol** [comment]
Just want to mention that @andyli once wrote this very nice article:
https://blog.onthewings.net/2010/12/19/method-chaining-and-fluent-interface-in-haxe/

**Comment by matulkum** [comment]
@markknol thanks for the link. Did not even see that before. So this is actually a pretty "ok" workaround for this case.

**Comment by EricBishton** [comment]
@markknol @andyli Perhaps, if Andy gives permission, a version of his article could make it into the Haxe cookbook on the web site (with appropriate attribution).

**Comment by andyli** [comment]
Feel free to take it to the cookbook. I'm glad that little post is still useful. :)

**Comment by RealyUniqueName** [comment]
I'd like to also be able to do this:
```haxe
class Some {
  static function doSomething():this {
    var inst = new this();
    return this;
  }
}
```
Which will allow to:
* Reduce amount of work on renaming types
* Simplify macros which need to operate with current type
* Simplify copy-pasting (bad side effect :) )

**Comment by RealyUniqueName** [comment]
We discussed this proposal and came to a conclusion it could be useful. However, @Simn has no clear vision how to implement it and needs to do a research first.
As for my previous comment about using `This` as the type expression, it should be a separate proposal.

**Comment by Simn** [comment]
What happens if the "this" class has type parameters?

**Comment by kevinresol** [comment]
I suppose it would always be the same as the "context"?

```haxe
$type(foo) == $type(foo.getThis()); // for all concrete T

class Base {
  function getThis():this;
}

class Foo<T> extends Base {}
```

**Comment by nadako** [comment]
I don't like method chaining, so I didn't care much about this proposal, but I just stumbled upon a piece of code where polymorphic `This` type could help. Just leaving it here for consideration and test case _if_ this is going to be implemented:

```haxe
class BaseButton {
  function setClickCallback(cb:This->Void);
}

class TabButton extends BaseButton {
  function someExtraApi();
}

// and then

var button = new TabButton();
button.setClickCallback(onTabClicked);

function onTabClicked(tab:TabButton) {
  tab.someExtraApi();
}
```

**Comment by Simn** [comment]
We didn't reach a consensus on this one in our haxe-evolution meeting yesterday.

There's agreement that this would be useful, but how to actually implement it remains unclear. I don't want to accept a proposal if I don't know to actually implement it, so for the time being this will remain open.

**Comment by kevinresol** [comment]
I also find this useful, but I can see a few unresolved questions:

1. Variance
```haxe
// currently this doesn't work because function arguments are contravariant
interface Base {
	function set(v:Base):Void;
}
interface Derived extends Base {
	function set(v:Derived):Void;
}

// Does that mean the compiler will reject the following?
interface Base {
	function set(v:This):Void;
}
```

2. How to detect something is of type `This`?

```haxe
class Base {
	public function get():This {
		return new Base(); // is this valid? If yes, it will break in derived classes, and they must override this method. Can the compiler detect this though?
	}
}
class Derived extends Base {
	public var derived:Int;
}

new Derived().get().derived; // runtime error: Base has no field derived
```


3. Implementation of interfaces

```haxe
interface Base {
	function get():This;
}

class BaseClass implements Base {
	public function get():BaseClass; // is this implementation valid? and how about derived classes/interfaces again?
}
```

**Comment by Simn** [comment]
lean-reject: too many unanswered questions

**Comment by Simn** [comment]
We have rejected the proposal in the haxe-evolution meeting today.

There have been long-standing open questions that have not been answered, which we interpret as the feature potentially being "nice to have", but not important enough to the general interest. Importantly, we do not reject the feature of a this-type per-se, but rather the proposal itself on these grounds. A new proposal that aims to answer open questions could lead to further discussions, and possibly acceptance.

**Pull request closed without merging**
