### PR TITLE
Local static

### PR DESCRIPTION
**Pull request by YellowAfterlife**
This had been on my mind for a while - I think allowing to declare "situational" static variables that are not visible outside of method is a good tradeoff between convenience and implementation costs.

[Rendered version](https://github.com/YellowAfterlife/haxe-evolution/blob/local-static/proposals/0000-local-static.md)

### CODE REVIEW

**Comment by Aurel300** [comment]
I have found myself kind of wanting this every now and then, and indeed, implementing it with macros for the important cases. On the other hand, this does introduce hidden state and makes reading code a bit less accessible to newcomers…

**Comment by hughsando** [comment]
I like it.  Although it has hidden state, the state is more obvious than if you declare the variable further away from the function.
This pattern is pretty common in C.

**Comment by Geokureli** [comment]
Would this mean that we could also have method scoped local inline vars, too or would that be a separate thing altogether?

**Comment by Simn** [comment]
This proposal has been accepted, see https://haxe.org/blog/evolution-meeting-2021/ for details.

**Pull request merged**
