### PR TITLE
Haxe Evolution: voting process adjustments

### PR DESCRIPTION
**Pull request by RealyUniqueName**
[Rendered proposal](https://github.com/RealyUniqueName/haxe-evolution/blob/voting-process/proposals/0000-voting-process.md)
[New section "Voting process" to README.md](https://github.com/RealyUniqueName/haxe-evolution/tree/voting-process#voting-process)

### CODE REVIEW

**Comment by RealyUniqueName** [comment]
Let's try it.

**Comment by RealyUniqueName** [comment]
Request for voting. @HaxeFoundation/evolution-voters

**Comment by Simn** [comment]
Works for me.

**Comment by andyli** [comment]
LGTM

**Comment by nadako** [comment]
Sounds good!

**Comment by hughsando** [comment]
cool

**Comment by waneck** [comment]
LGTM!

**Comment by ncannasse** [comment]
good for me

**Pull request merged**
